[CD] Do not enable GenAI on Windows
Follow up after https://github.com/pytorch/pytorch/pull/162209 as looks
like it causes some of the Windows builds to fail with
```
C:/actions-runner/_work/pytorch/pytorch/pytorch/third_party/fbgemm/fbgemm_gpu/experimental/gen_ai/src/quantize/common/include\fbgemm_gpu/quantize/utils.h(19): error C3861: '__builtin_clz': identifier not found
```

ghstack-source-id: 31460acfa69979a2d5c6769c314e2a9c9e66b4b6
Pull Request resolved: https://github.com/pytorch/pytorch/pull/163116